# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Colección Ida Esbra'
description:      'Colección fotográfica de la obra de Ida Esbra'
url:              'https://lucylopezpa.github.io' # Reemplazar por cuenta de github propia
baseurl:          '/plantilla-wax' # Reemplazar por nombre del repositorio
copyright:        'Derechos reservados, 2024'
logo:             '/assets/logo.png'
default_thumb:    '/assets/default.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude: ["Gemfile*", "*.gemspec", "Rakefile", "vendor", "spec", "README.md", "LICENSE.txt", "Docker*"]
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  america: # OJO: Cambiar por nombre de la colección
    output: true
    layout: 'plantilla_item' # npmbre de la plantilla con la estructura de los ítems de la colección
    metadata:
      source: 'america.csv' # nombre del archivo con metadatos guardado en `_data`
    images:
      source: 'raw_images/america' # ruta de la carpeta con imágenes guardada en `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json'
    collections:
      america: # OJO: Cambiar por nombre de la colección
        content: false
        fields: # Metadatos que se indexarán
          - label
          - identifier
          - title
          - creator
          - date
          - description

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu: # Elementos que irán en el menú superior
  - label: 'Acerca'
    link: '/acerca/'
  - label: 'Exhibiciones'
    sub:
      - label: 'Muestra A'
        link: '/exhibits/muestra/'
  - label: 'Explorar'
    link: '/explorar/'
  - label: 'Buscar'
    link: '/buscar/'
  - label: 'Metadatos'
    link: '/metadatos/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer: # Elementos que irán en el menú inferior
  links:
    - label: 'Créditos'
      link: '/creditos'
  logos:
    - img: '/img/logo.png'

# FIN